### ISSUE TITLE
msg.match is not a function

### ISSUE THREAD

**Issue by sistematico** [cirry/astro-yi#21] opened 2024-09-04 12:26 UTC
```
bunx --bun astro dev
msg.match is not a function. (In 'msg.match(/ec\.config\.mjs.*(imported from|resolved id)/)', 'msg.match' is undefined)
  Stack trace:
    at <anonymous> (/home/lucas/code/blog.paxa.dev/node_modules/astro-expressive-code/dist/index.js:39:17)
error: script "dev" exited with code 1
```

No clues at this point.

**Comment by cirry** [comment] 2024-09-09 09:52
It can't be reproduced, you can upgrade the project to try it out

**Comment by cirry** [comment] 2024-10-22 03:50
This was caused by not configuring the site.url attribute in const.ts, which is now fixed

**Closed by cirry** 2024-10-22 03:50 UTC
